#!/usr/bin/env bash
# generated by make_contigs.py - run from the RFdiffusion repo root
set -euo pipefail
RFD="${RFD:-.}"
OUT="${OUT:-./rfd_out}"
mkdir -p "$OUT"

# cperm_link01
python "$RFD/scripts/run_inference.py" \
    inference.input_pdb=inputs/monomer.pdb \
    inference.output_prefix="$OUT/cperm_link01" \
    'contigmap.contigs=[A133-176/5-5/A3-122/7-7/A130-132]' \
    inference.num_designs=5 \
    denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0

# cperm_link02
python "$RFD/scripts/run_inference.py" \
    inference.input_pdb=inputs/monomer.pdb \
    inference.output_prefix="$OUT/cperm_link02" \
    'contigmap.contigs=[A133-176/6-6/A3-122/7-7/A130-132]' \
    inference.num_designs=5 \
    denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0

# cperm_link03
python "$RFD/scripts/run_inference.py" \
    inference.input_pdb=inputs/monomer.pdb \
    inference.output_prefix="$OUT/cperm_link03" \
    'contigmap.contigs=[A133-176/7-7/A3-122/7-7/A130-132]' \
    inference.num_designs=5 \
    denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0

# cperm_link04
python "$RFD/scripts/run_inference.py" \
    inference.input_pdb=inputs/monomer.pdb \
    inference.output_prefix="$OUT/cperm_link04" \
    'contigmap.contigs=[A133-176/8-8/A3-122/7-7/A130-132]' \
    inference.num_designs=5 \
    denoiser.noise_scale_ca=0 denoiser.noise_scale_frame=0
